name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.4.4', '8.6.5', '8.8.3' ]
        cabal: [ '3.0' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-cabal-store-cabal${{ matrix.cabal }}-ghc${{ matrix.ghc }}

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build all --only-dependencies --enable-tests
    - name: Build
      run: cabal v2-build all
    - name: Run tests
      run: cabal v2-test all

  cabal-format:
    name: check .cabal style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-haskell@v1
        with:
          cabal-version: '3.2'
      - run: cabal format
      - run: git diff --exit-code
