name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: [ '8.8.4', '8.10.7', '9.0.1' ]
        cabal: [ 'latest' ]
        allow-failure: [ false ]
        cabal-options:
          - '--constraint="aeson < 2"'
          - '--constraint="aeson >= 2"'
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-cabal-store-cabal${{ matrix.cabal }}-ghc${{ matrix.ghc }}

    - name: Install dependencies
      run: |
        cabal v2-update
        cabal v2-build all --only-dependencies --enable-tests ${{ matrix.cabal-options }}
    - name: Build
      run: cabal v2-build all ${{ matrix.cabal-options }}
    - name: Run tests
      run: cabal v2-test all ${{ matrix.cabal-options }}

  hlint:
    name: lint *.hs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install hlint
        run: sudo apt-get install hlint

      - run: hlint $(git ls-tree -r HEAD | awk '$4 ~ /\.hs/{ print $4}' | grep -vE '^Warning.hs$|^(tests|sample)/.*')
